# Generated by Django 3.2.8 on 2021-10-17 20:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211013_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Вариант №1'), (2, 'Вариант №2'), (3, 'Вариант №3')], max_length=5),
        ),
    ]
